name: Build and Deploy Container to Azure Web App - InvoiceTest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Permissions are required for the secure OIDC login to Azure
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2EB9B3F9DB8A44FE8536A3107F2ABAD4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_53DA8E675EFE4A0B9B5E37AF07AAB4E5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_007C89AD0D344198AF77A056C302470C }}

      - name: Log in to container registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/invoicetest:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/invoicetest:${{ github.sha }}

  deploy-to-app-service:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    # Permissions are also required for the deploy job
    permissions:
      id-token: write
    
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2EB9B3F9DB8A44FE8536A3107F2ABAD4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_53DA8E675EFE4A0B9B5E37AF07AAB4E5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_007C89AD0D344198AF77A056C302470C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'InvoiceTest'
          images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/invoicetest:${{ github.sha }}'
